[[social]]
identifier = "github"
name = "Github"
url = "https://github.com/ShadowObj/blog"
params.icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/objectshadow"
params.icon = "brand-twitter"

[[social]]
identifier = "telegram"
name = "Telegram"
url = "https://t.me/objshadow"
params.icon = "brand-telegram"

[[social]]
identifier = "signal"
name = "Signal"
url = "https://signal.me/#eu/1-a3Slz1elCbLBF_RkBBZbhlwoA47hFcTChiP7lq_2yrjuoClBJFF6ZF_ij4ORo_"
params.icon = "brand-signal"

[[social]]
identifier = "pgpkey"
name = "PGP Key"
url = "https://keys.openpgp.org/vks/v1/by-fingerprint/FDEAA5F05C3B8D3A9A96DC7DE4465C42D44B171A"
params.icon = "brand-key"

[[main]]
name = "RSS"
url = "/index.xml"
weight = -40
params.icon = "rss"