[[social]]
identifier = "rss"
name = "RSS"
url = "/index.xml"
params.icon = "rss"
weight = -100

[[social]]
identifier = "github"
name = "Github"
url = "https://github.com/ShadowObj/blog"
params.icon = "brand-github"
weight = -90

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/objectshadow"
params.icon = "brand-twitter"
weight = -80

[[social]]
identifier = "telegram"
name = "Telegram"
url = "https://t.me/objshadow"
params.icon = "brand-telegram"
weight = -70
