[[social]]
identifier = "rss"
name = "RSS"
url = "/en/index.xml"
params.icon = "rss"
weight = -100

[[social]]
identifier = "github"
name = "Github"
url = "https://github.com/ObjShadow/blog"
params.icon = "brand-github"
weight = -90

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/objectshadow"
params.icon = "brand-twitter"
weight = -80

[[social]]
identifier = "telegram"
name = "Telegram"
url = "https://objshadow.t.me/"
params.icon = "brand-telegram"
weight = -70
